apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: bus-tracking
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "transitpulse"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  OLLAMA_BASE_URL: "http://ollama:11434"
  AI_PREDICTION_SERVICE_URL: "http://ai-prediction-service:8086"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8087"
  SPRING_PROFILES_ACTIVE: "k8s"
